version: '3.7'

volumes:
  webapi-volume:
  db-volume:
    driver: local

services:
  webapi:
    ports: 
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    build:
      context: .
      dockerfile: ./docker/webapi/Dockerfile
    restart: always
    volumes:
      - webapi-volume:/app

  local-mongo:
    image: mongo
    ports:
     - "27017:27017"
    restart: always
    volumes:
     - db-volume:/data/db
