version: '3.7'

volumes:
  db-volume:
    driver: local

services:
  webapi:
    ports: 
      - "127.0.0.1:8080:8080"
    environment:
      - Database__Host=local-mongo
      - ASPNETCORE_URLS=http://+:8080
    build:
      context: .
      dockerfile: ./docker/webapi/Dockerfile
    restart: always

  front:
    ports:
      - "127.0.0.1:3000:3000"
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    restart: always

  local-mongo:
    image: mongo
    ports:
     - "127.0.0.1:27017:27017"
    restart: always
    volumes:
     - db-volume:/data/db
