version: '3.7'

volumes:
  webapp-volume:
  db-volume:
    driver: local

services:
  webapp:
    ports: 
      - "8080:8080"
    build:
      context: .
      dockerfile: ./docker/webapp/Dockerfile
    restart: always
    volumes:
      - webapp-volume:/webapp

  local-mongo:
    image: mongo
    ports:
     - "27017:27017"
    restart: always
    volumes:
     - db-volume:/data/db
